In [2]:
import pandas as pd
import numpy as np
import os

In [92]:
files = os.listdir('Results/Cluster2')
full_result2 = pd.DataFrame()
for file in files:
    result = pd.read_csv('Results/Cluster2/' + file, index_col=0)
    full_result2 = pd.concat([result, full_result2])
full_result2.reset_index(inplace=True, drop=True)

In [93]:
i = np.linspace(0, 27, 10).astype(int)

In [101]:
full_result2.sort_values(by=['f1', 'bal_acc'], axis=0, ascending=False).iloc[i, :]

,t,n,depth,bal_acc,f1,Precision,Recall,Bagging,Feature,sum_f1_acc
272,0.45,700,2,0.692124,0.597283,0.505268,0.730272,0.8,1.0,1.289406
191,0.45,50,10,0.691360,0.596833,0.502445,0.734887,0.8,1.0,1.288194
1541,0.45,75,10,0.692098,0.596662,0.508535,0.721735,0.8,1.0,1.288760
1197,0.50,200,3,0.695391,0.596585,0.535721,0.673050,0.8,0.8,1.291975
1297,0.45,100,10,0.692642,0.596416,0.513938,0.710429,0.8,0.9,1.289058
703,0.45,400,3,0.691618,0.595777,0.510023,0.716198,0.8,0.9,1.287396
1540,0.45,75,10,0.691324,0.595659,0.508571,0.718736,0.8,0.9,1.286983
1631,0.50,75,4,0.694010,0.595417,0.531114,0.677434,0.8,1.0,1.289426
1270,0.45,100,15,0.691816,0.595361,0.513821,0.707660,0.8,0.9,1.287176
1567,0.45,75,7,0.691116,0.595263,0.509270,0.716198,0.8,0.9,1.286379

In [100]:
full_result2.sort_values(by=['bal_acc', 'f1'], axis=0, ascending=False).iloc[i, :]

,t,n,depth,bal_acc,f1,Precision,Recall,Bagging,Feature,sum_f1_acc
1197,0.50,200,3,0.695391,0.596585,0.535721,0.673050,0.8,0.8,1.291975
1576,0.50,75,7,0.694033,0.593919,0.541176,0.658053,0.8,0.9,1.287952
1631,0.50,75,4,0.694010,0.595417,0.531114,0.677434,0.8,1.0,1.289426
1523,0.50,75,15,0.693973,0.594113,0.539330,0.661283,0.8,1.0,1.288086
1333,0.50,100,7,0.693844,0.593029,0.545419,0.649746,0.8,0.9,1.286873
954,0.50,300,3,0.693839,0.594131,0.537987,0.663359,0.8,0.8,1.287970
837,0.45,300,10,0.693713,0.593918,0.538245,0.662437,0.8,0.8,1.287631
1577,0.50,75,7,0.693664,0.593623,0.539754,0.659437,0.8,1.0,1.287288
1415,0.50,100,4,0.693526,0.594173,0.534909,0.668205,0.8,1.0,1.287699
65,0.50,50,15,0.693459,0.594318,0.533382,0.670974,0.8,1.0,1.287778

In [103]:
files = os.listdir('Results/Cluster1_1')
full_result1 = pd.DataFrame()
for file in files:
    result = pd.read_csv('Results/Cluster1_1/' + file, index_col=0)
    full_result1 = pd.concat([result, full_result1])

files = os.listdir('Results/Cluster1_2')
for file in files:
    result = pd.read_csv('Results/Cluster1_2/' + file, index_col=0)
    full_result1 = pd.concat([result, full_result1])

full_result1.reset_index(inplace=True, drop=True)

In [104]:
full_result1.sort_values(by=['f1', 'bal_acc'], axis=0, ascending=False).iloc[i, :]

,t,n,depth,bal_acc,f1,Precision,Recall,Bagging,Feature
1422,0.55,100,2,0.658073,0.361328,0.290424,0.478036,0.8,0.8
856,0.55,50,1,0.651600,0.357873,0.296108,0.452196,0.8,0.9
1179,0.55,300,2,0.651600,0.357873,0.296108,0.452196,0.8,0.8
1396,0.55,100,3,0.651421,0.357508,0.295608,0.452196,0.8,0.9
855,0.55,50,1,0.650448,0.357438,0.297762,0.447028,0.8,0.8
1423,0.55,100,2,0.657868,0.357278,0.281669,0.488372,0.8,0.9
1476,0.55,50,15,0.639933,0.356974,0.328976,0.390181,0.8,0.8
749,0.55,75,3,0.654376,0.356863,0.287520,0.470284,0.8,1.0
1477,0.55,50,15,0.640368,0.355814,0.323467,0.395349,0.8,0.9
1395,0.55,100,3,0.648798,0.355005,0.295533,0.444444,0.8,0.8

In [87]:
full_result1.sort_values(by=['bal_acc', 'f1'], axis=0, ascending=False).iloc[i, :]

,t,n,depth,bal_acc,f1,Precision,Recall,Bagging,Feature
0,0.45,75,2,0.678606,0.334975,0.219887,0.702842,0.8,0.8
567,0.45,200,1,0.675178,0.335682,0.223169,0.677003,0.8,0.8
819,0.50,50,2,0.674268,0.353668,0.252203,0.591731,0.8,0.8
568,0.45,200,1,0.672990,0.333546,0.221562,0.674419,0.8,0.9
2,0.45,75,2,0.672722,0.330049,0.216653,0.692506,0.8,1.0
325,0.45,400,1,0.671007,0.333550,0.222997,0.661499,0.8,0.9
839,0.45,50,1,0.670713,0.334656,0.224889,0.653747,0.8,1.0
1,0.45,75,2,0.670278,0.328580,0.216150,0.684755,0.8,0.9
1404,0.45,100,2,0.670240,0.328972,0.216749,0.682171,0.8,0.8
1432,0.45,100,1,0.669984,0.329560,0.217789,0.677003,0.8,0.9

In [97]:
full_result1['sum_f1_acc'] = full_result1['f1'] + full_result1['bal_acc']
full_result2['sum_f1_acc'] = full_result2['f1'] + full_result2['bal_acc']

In [90]:
full_result1.sort_values(by=['sum_f1_acc'], axis=0, ascending=False).iloc[i, :]

,t,n,depth,bal_acc,f1,Precision,Recall,Bagging,Feature,sum_f1_acc
819,0.50,50,2,0.674268,0.353668,0.252203,0.591731,0.8,0.8,1.027936
1422,0.55,100,2,0.658073,0.361328,0.290424,0.478036,0.8,0.8,1.019401
1176,0.50,300,2,0.664507,0.353441,0.263291,0.537468,1.0,0.8,1.017948
1429,0.55,100,2,0.657868,0.357278,0.281669,0.488372,1.0,0.9,1.015146
0,0.45,75,2,0.678606,0.334975,0.219887,0.702842,0.8,0.8,1.013581
821,0.50,50,2,0.667565,0.344985,0.244349,0.586563,0.8,1.0,1.012550
1576,0.50,50,4,0.660120,0.351399,0.265522,0.519380,0.8,0.9,1.011518
749,0.55,75,3,0.654376,0.356863,0.287520,0.470284,0.8,1.0,1.011238
567,0.45,200,1,0.675178,0.335682,0.223169,0.677003,0.8,0.8,1.010860
1182,0.55,300,2,0.651600,0.357873,0.296108,0.452196,0.9,0.8,1.009473

In [98]:
full_result2.sort_values(by=['sum_f1_acc'], axis=0, ascending=False).iloc[i, :]

,t,n,depth,bal_acc,f1,Precision,Recall,Bagging,Feature,sum_f1_acc
1197,0.50,200,3,0.695391,0.596585,0.535721,0.673050,0.8,0.8,1.291975
1637,0.50,75,4,0.694010,0.595417,0.531114,0.677434,1.0,1.0,1.289426
272,0.45,700,2,0.692124,0.597283,0.505268,0.730272,0.8,1.0,1.289406
1297,0.45,100,10,0.692642,0.596416,0.513938,0.710429,0.8,0.9,1.289058
1544,0.45,75,10,0.692098,0.596662,0.508535,0.721735,0.9,1.0,1.288760
194,0.45,50,10,0.691360,0.596833,0.502445,0.734887,0.9,1.0,1.288194
1094,0.50,50,4,0.693090,0.595098,0.525349,0.686202,0.9,1.0,1.288187
1523,0.50,75,15,0.693973,0.594113,0.539330,0.661283,0.8,1.0,1.288086
957,0.50,300,3,0.693839,0.594131,0.537987,0.663359,0.9,0.8,1.287970
1582,0.50,75,7,0.694033,0.593919,0.541176,0.658053,1.0,0.9,1.287952